# Why is NumPy Faster? 

- Faster to read fewer bytes of memory
- No type-checking when iterating through objects
- Contiguous Memory

# How are Lists different from Numpy?

Lists: Insertion, deletion, appending, concatenation
NumPy: Insertion, deletion, appending, concatenation, etc.

# Load in NumPy (remember to pip install numpy first)



In [2]:
import numpy as np

# The Basics

In [8]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [10]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [12]:
# Get Dimension
a.ndim # 1
b.ndim # 2

2

In [15]:
# Get Shape
a.shape #(3,)
b.shape #(2, 3)

(2, 3)

In [19]:
# Get Type
a.dtype #('int32')

dtype('int32')

In [23]:
# Get Szie
a.itemsize # (4 * 1byte)

4

In [22]:
# Get total szie
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [4]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# Get a specific element [row, column]
a[1, 5]
a[1, -2]

13

In [10]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [19]:
# Getting a little more fancy [start_index:end_index:step_size]
a[0, 1:6:2]
a[0, 1:-1:2]

array([2, 4, 6])

In [21]:
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


**3D example**

In [27]:
b = np.array([[[1, 2],[3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [30]:
# Get a specific element (work outside in)
b[0, 1, 1]

4

In [38]:
# replace 
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initialising Different Types of Arrays

In [43]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [50]:
# Any other number
np.full((2,2,), 99)

array([[99, 99],
       [99, 99]])

In [53]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [59]:
# Random decimal numbers
np.random.rand(4,2,3)
np.random.random_sample(a.shape)

array([[0.58782296, 0.91265196, 0.23096222, 0.81766828, 0.61806651,
        0.15153659, 0.80635701],
       [0.22459737, 0.84095573, 0.05724721, 0.05996248, 0.48727477,
        0.34476009, 0.55876431]])

In [68]:
# Random Integer values
np.random.randint(-2, 8, size=(3,3))

array([[ 6,  6,  7],
       [-2, -2,  0],
       [ 5, -1,  1]])

In [70]:
# The identity martrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
# Reapeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [83]:
output = np.ones((5,5))
print(output)


z = np.zeros((3,3,))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays

In [91]:
a = np.array([1, 2, 3])
# b = a
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


# Mathematics

In [102]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [100]:
# a + 2
a += 2
a

array([ 9, 10, 11, 12])

In [94]:
a - 2

array([-1,  0,  1,  2])

In [95]:
a * 2

array([2, 4, 6, 8])

In [96]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [103]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [104]:
a ** 2

array([ 1,  4,  9, 16])

In [106]:
# Take the sin
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### For a Lot more  
- Code: https://github.com/KeithGalli/NumPy
- 🔗 Indexing: https://docs.scipy.org/doc/numpy-1.13...
- 🔗 Array Creation Routines: https://docs.scipy.org/doc/numpy/refe...
- 🔗 Math Routines Docs: https://docs.scipy.org/doc/numpy/refe...
- 🔗 Linear Algebra Docs: https://docs.scipy.org/doc/numpy/refe...
