## Array fundamentals
One way to initialise an array is using a Python sequence, such as a list. For example:

In [13]:
import numpy as np

In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [18]:
# Like the original list, the array is mutable.
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [23]:
# Also like the original list, Python slice notation can be used for indexing
a[:3]

array([10,  2,  3])

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [30]:
b = a[3:]
b

array([4, 5, 6])

In [33]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [36]:
# Two- and higher-dimensional arrays can be initialised from nested Python sequences:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In NumPy, a dimension of an array is sometimes referred to as an 'axis'. This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. For instance, the array `a` could represent three points, each lying within a four-dimensional space, but `a` has only two 'axes'.

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element `8` is in row `1` and column `3`:

In [43]:
a[1, 3]

8