# How to create a basic array 
This section covers `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`

Besides creating an array from a sequence of elements, you can easily create an array filled with `0`'s:

In [10]:
import numpy as np

In [12]:
np.zeros(2)

array([0., 0.])

Or an array filled with `1`'s:

In [19]:
np.ones(2)

array([1., 1.])

Or even an empty array! The function `empty` creates an array whose initial content is random and depends on the state of the memory. The reason to use `empty` over `zeros`(or something similar) is speed - just make sure to fill every element afterwards!

In [34]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

You can create an array with a range of elements:

In [39]:
np.arange(4)

array([0, 1, 2, 3])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the **first number**, **last number**, and the **step size**.

In [43]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

You can also use `np.linspace()` to create an array with values that are spaced linearly in a specified interval:

In [46]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Specifying your data type**

While the default data type is floating point(`np.float64`), you can explicitly specify which data type you want using the `dtype` keyword.

In [49]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])