# Adding, removing, and soring elemnets
This section covers `np.sort()`, `np.concatenate()`
Sorting an array is simple with `np.sort()`. You can specify the axis, kind, and order when you call the function.
If you start with this array:

In [12]:
import numpy as np

If you start with this array:

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

You can quickly sort the numbers in ascending order with:

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In addition to sort, which returns a sorted copy of an array, you can use:
- [`argsort`](https://numpy.org/dox/stable/reference/generated/numpy.argsort.html#numpy.argsort), which is an indirect sort along a specified xis,
- [`lexsort`](https://numpy.org/dox/stable/reference/generated/numpy.lexsort.html#numpy.lexsort), which is an indirect stable sort on multiple keys,
- [`searchsorted`](https://numpy.org/dox/stable/reference/generated/numpy.searchsorted.html#numpy.searchsorted), which will find elements in a sorted array, and
- [`partition`](https://numpy.org/dox/stable/reference/generated/numpy.partition.html#numpy.partition), which is a partial sort.

To read more about sorting an array, see: [`sort`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html#numpy.sort).

If you start with these arrays:

In [35]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with `np.concatenate()`.

In [38]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

Or, if you start with these arrays:

In [41]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

You can concatenate them with:

In [46]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In order to remove elements from an array, it's simple to use indexing to select the elements that you want to keep.
To read more about concatenate, see: [`concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate).