# Can you reshape an array?
This section covers `arr.reshape()`

**Yes!**

Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when you sue the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you'll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [18]:
import numpy as np
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


You can use `reshape()` to reshape your array. For example, you can reshape this array to an array with three rows and two columns:

In [21]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


With `np.reshape`, you can specify a few optional parameters:

In [37]:
np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

`a` is the array to be reshaped.

`shape` is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

`order:` `c` means to read/write the elements using C-like index order, `F` means to read/write the elements using Fortran-like index order, `A` means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn't need to be specified.)